apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-backend-service
spec:
  selector:
    app: {{ .Chart.Name }}-backend
  ports:
  - port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-frontend-service
spec:
  selector:
    app: {{ .Chart.Name }}-frontend
  ports:
  - port: {{ .Values.frontend.port }}
    targetPort: {{ .Values.frontend.port }}
  type: NodePort
