apiVersion: apps/v1
kind: Deployment
metadata:
  name: djerba-backend
  namespace: djerba
spec:
  replicas: 2
  selector:
    matchLabels:
      app: djerba-backend
  template:
    metadata:
      labels:
        app: djerba-backend
    spec:
      containers:
        - name: backend
          image: djerba-backend:1.0
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
