apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: djerba-ingress
  namespace: djerba
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: app.lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: djerba-frontend-service
            port:
              number: 80
