name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Backend
        run: mvn clean package -DskipTests -f backend/pom.xml

      - name: Build Docker images
        run: |
          docker build -t djerba-backend:1.0 -f Dockerfile-backend .
          docker build -t djerba-frontend:1.0 -f Dockerfile-frontend .

      - name: Push to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag djerba-backend:1.0 ${{ secrets.DOCKER_USERNAME }}/djerba-backend:1.0
          docker tag djerba-frontend:1.0 ${{ secrets.DOCKER_USERNAME }}/djerba-frontend:1.0
          docker push ${{ secrets.DOCKER_USERNAME }}/djerba-backend:1.0
          docker push ${{ secrets.DOCKER_USERNAME }}/djerba-frontend:1.0
